### ISSUE TITLE
when storymap data is uploaded to CSV, do not call googleDocURL

### ISSUE THREAD

**Issue by JackDougherty** [OnTheLine/otl-urban-renewal-new-london#1]
@ilyankou whenever you have time to look at this non-urgent issue, I *think* you designed the code to address this, but I cannot figure out how to make it work properly

Goal: To "archive" this storymap, I have migrated Chapters and Options data from GoogleSheet to CSV folder in GitHub.
Now I want the code to (a) ignore the existence of the GoogleSheet and (b) **NOT** point to the googleDocURL in the "data by" attribution, as shown here:
![Screenshot 2024-03-21 at 11 29 48 AM](https://github.com/OnTheLine/otl-urban-renewal-new-london/assets/649719/974347d7-cea8-4eef-b418-df54fd34f7f8)

Years ago, I *think* you designed the code to address this issue when you wrote this section:
https://github.com/OnTheLine/otl-urban-renewal-new-london/blob/539e92781cff30ee73ad2755ee6a390a036e60ca/scripts/storymap.js#L483

If so, then I cannot figure out how to set the googleDocURL to empty (or whatever), in order for it to link to Chapters.csv

So far I have tried two methods in the google-doc-url.js file, but neither seems to work for me:

`var googleDocURL = '';`
and
`var googleDocURL = null;`

More about Goal part (a): 
Overall, I've noticed that the code behaves differently on GitHub Pages online versus my local Firefox test setup, as shown in the side-by-side screenshots below. Even when the data is uploaded as CSV, the Firefox setup continues to display the Google Sheets data. Not a deal breaker, but wonder if this might be a related issue, so decided to mention it.
![Screenshot 2024-03-21 at 11 46 51 AM](https://github.com/OnTheLine/otl-urban-renewal-new-london/assets/649719/3aeac305-8a5f-4e10-948f-e72ff29dc182)

**Comment by ilyankou** [comment]
Hi @JackDougherty 

I think the issue is with the browser not being able to access the CSV file when you open index.html locally by double-clicking. You will need to run a local server, for example either via Python:

```bash
cd otl-urban-renewal-new-london # navigate to the project folder here
python -m http.server
```

(and then type localhost:8000 in Firefox)

or use a tool like [`live-server`](https://github.com/tapio/live-server). This will ensure that your local setup mimics server behaviour (what you see on GitHub etc).

<img width="1226" alt="Screenshot 2024-03-21 at 16 28 39" src="https://github.com/OnTheLine/otl-urban-renewal-new-london/assets/10443203/6262a2db-4205-4e1d-8b91-4950c986d103">
<img width="1226" alt="Screenshot 2024-03-21 at 16 28 30" src="https://github.com/OnTheLine/otl-urban-renewal-new-london/assets/10443203/061118e1-9940-4a2f-affb-4ddb77f80727">

**Comment by JackDougherty** [comment]
@ilyankou - Many thanks for the http.server tutorial, which solved part (a) of my issue, and allowed me to test a successful result for part (b), which I'll add to our HandsOnDataViz book, unless you tell me otherwise:

After migrating storymap data from your Google Sheet by uploading `Chapter.csv` and `Options.csv` files to the GitHub CSV folder, go to the `google-doc-url.js` file and replace the variable for the Google Sheet URL to null:
`var googleDocURL = null;`
